name: Test application generation

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run prettier check
        run: npm run prettier:check

  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run eslint check
        run: npm run lint

  app-build-check:
    name: Build application
    needs: [jest-check]
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: ${{ secrets.SKIP_ENV_VALIDATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
        env:
          CI: true
